#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

errmsg()
{
    echo >&2 ''
    echo >&2 "$@"
    echo >&2 "try 'dpkg-reconfigure debconf' to select a frontend other than noninteractive"
    echo >&2 ''
}

DPKG_MAINTSCRIPT_PACKAGE=ros-indigo-darknet

WEIGHTS_DIR=/opt/ros/$(echo $DPKG_MAINTSCRIPT_PACKAGE| sed 's/^ros-\(.*\)-.*$/\1/')/share/darknet/weights/
echo >&2 ''
echo >&2 "$@"
echo >&2 "Download weights files to $WEIGHTS_DIR"
echo >&2 ''
mkdir -p $WEIGHTS_DIR
cd $WEIGHTS_DIR; [ ! -e yolo.weights ] && wget http://pjreddie.com/media/files/yolo.weights

exit 0

